server:
  port: 8090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board
    username: root
    password: 12345
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      connection:
        CharSet: utf-8
        characterEncoding: utf-8
        useUnicode: true
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        show_sql: true
        format_sql: true

